services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: notes
      POSTGRES_PASSWORD: notes
      POSTGRES_DB: notes
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongo:
    image: mongo:8
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - mongo_data:/data/db
volumes:
  postgres_data:
  mongo_data:
